{% set prefix = "spacy-model-" %}
{% set lang = "de" %}

{% if size == "trf" %}
{% set name = lang + "_dep_news" %}
{% else %}
{% set name = lang + "_core_news" %}
{% endif %}

{% set version = "3.5.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-{{ version }}/de_core_news_sm-{{ version }}.tar.gz
    sha256: 77e149602f13d8c663355a5f54b9d53d563891709747e3852224a3dd148e98e2
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-{{ version }}/de_core_news_lg-{{ version }}.tar.gz
    sha256: 401952e872572a0881d1e7ca6cd3b97ac6333a38c30622eb596aba3e0a7a7a50
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_md-{{ version }}/de_core_news_md-{{ version }}.tar.gz
    sha256: d5f7c2dcd6a5b838128c8399098ef61e3d871c8543f1df88185c9199ca5be907
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/de_dep_news_trf-{{ version }}/de_dep_news_trf-{{ version }}.tar.gz
    sha256: 9609e85c5ee9c1bf3534902755285bc9f6bad1a93d0d3b3dc7d08f627e9bbb34

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}

    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}
      commands:
        {% if size == "trf" %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"  # [unix]
        {% else %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"
        {% endif %}

about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: German multi-task CNN trained on the TIGER and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/de

extra:
  recipe-maintainers:
    - FernandezMathieu
    - mxr-conda
    - JennaLipscomb
    - sodre
