{% set prefix = "spacy-model-" %}
{% set lang = "de" %}

{% if size == "trf" %}
{% set name = lang + "_dep_news" %}
{% else %}
{% set name = lang + "_core_news" %}
{% endif %}

{% set version = "3.4.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-{{ version }}/de_core_news_sm-{{ version }}.tar.gz
    sha256: 33b8c16beaa2e6045bb6d91611dcb693cffec548f570755d7334d3a148def5a2
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-{{ version }}/de_core_news_lg-{{ version }}.tar.gz
    sha256: 797b0f5d709e5cbc446c70c15b21a20a5af004f49920c6b21ccf89c3f5501600
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/de_core_news_md-{{ version }}/de_core_news_md-{{ version }}.tar.gz
    sha256: eab9e19b1a13d3df8471886ac677718ea3765190bb703ed35323da062e0512c6
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/de_dep_news_trf-{{ version }}/de_dep_news_trf-{{ version }}.tar.gz
    sha256: dc47a15f6ffd439c3eeb3756e84777164dfb0c7176e957358c1b0ecf94581dd2

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}

    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}
      commands:
        {% if size == "trf" %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"  # [unix]
        {% else %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"
        {% endif %}

about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: German multi-task CNN trained on the TIGER and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/de

extra:
  recipe-maintainers:
    - FernandezMathieu
    - mxr-conda
    - JennaLipscomb
    - sodre
